name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install OS deps for Qt (offscreen)
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-x11-0

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt -r requirements-dev.txt
          if [ -f requirements-qt.txt ]; then python -m pip install -r requirements-qt.txt; fi

      - name: Install from lock (reproducible)
        run: |
          python -m pip install -r requirements-lock.txt
          python -m pip freeze | sed -n '1,50p'

      - name: Dependency audit (non-fatal)
        continue-on-error: true
        run: |
          python -m pip install pip-audit || exit 0
          pip-audit || exit 0

      - name: Lint (ruff)
        run: ruff .

      - name: Type check (mypy, warn-only)
        continue-on-error: true
        run: mypy .

      - name: Static security scan
        run: python tools/static_security_check.py

      - name: Run provider tests (headless Qt)
        env:
          QT_QPA_PLATFORM: offscreen
        run: pytest -q -m providers

      - name: Run GUI smoke tests (guarded)
        env:
          QT_QPA_PLATFORM: offscreen
        run: pytest -q -m gui


